baseURL: "https://cards.crashdive.co.uk/"
title: "Crash Dive - Cards"
languageCode: "en-GB"
disableKinds: ["taxonomy", "RSS"]
enableRobotsTXT: true
disableHugoGeneratorInject: true
build:
  noJSConfigInAssets: true
sitemap:
    changefreq: monthly
module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "node_modules/tabulator-tables/dist/css"
      target: "assets/css/tabulator-tables"
